title: Speech AI Deadlines
remark: Speech-oriented

description: Countdowns to top Speech conferences and workshops
author: Haohan Guo
maintainers: Haohan Guo

domain: "hhguo.github.io/speech-ai-deadlines/"
baseurl: "speech-ai-deadlines"

github_username: hhguo
github_repo: speech-ai-deadlines

markdown: kramdown
